# Generated by Django 3.0.3 on 2020-04-08 20:58

from django.db import migrations,models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Done',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Grade'),
        ),
        migrations.AddField(
            model_name='File',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Grade'),
        ),
        migrations.AddField(
            model_name='Subject',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Grade'),
        ),

    ]
