# Generated by Django 3.0.4 on 2020-03-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200329_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='schedule',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
