# Generated by Django 3.0.3 on 2020-03-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_subject_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='schedule',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
