# Generated by Django 3.0.3 on 2020-03-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20200330_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='days',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
