# Generated by Django 3.0.3 on 2020-04-14 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 17, 28, 35, 78869, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 17, 28, 35, 78905, tzinfo=utc)),
        ),
    ]
