# Generated by Django 3.0.3 on 2020-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_subject_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
