# Generated by Django 3.0.3 on 2020-04-15 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200414_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 14, 43, 28, 471565, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 14, 43, 28, 471643, tzinfo=utc)),
        ),
    ]
