# Generated by Django 3.0.3 on 2020-03-31 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20200330_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Subject'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
